//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNm2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI
    {
        public int Id { get; set; }
        public System.DateTime DateCreaNCI { get; set; }
        public string CreateurNCI { get; set; }
        public string Zone { get; set; }
        public string TitreNCI { get; set; }
        public string CommentNCI { get; set; }
        public string ActionNCI { get; set; }
        public Nullable<System.DateTime> DateTermine { get; set; }
        public bool Termine { get; set; }
    }
}
